#!/usr/bin/env bash

# gh-doccs = GitHub documentation codespace
# This extension for GitHub CLI creates a codespace for the docs-internal repo.
# Use: gh doccs
# Created by Alistair Christie (@hubwriter) 2023-01-26

set -e

SCRIPTNAME=$(basename "$0" .sh)
REPO="github/docs-internal"
DEVCONTAINER=".devcontainer/devcontainer.json"
TIMEOUT="3h"
MACHINE="xLargePremiumLinux" # To list available machine types for a repo use:
                             # gh api --jq ".machines[].name" repos/OWNER/REPONAME/codespaces/machines
RETENTION="720h"
OPEN_IN_BROWSER=false # Set to true to open the codespace in a browser, or false to open in VS Code.
REQUEST_BRANCH=true # Set to true to request a branch name, or false to use the default branch.

display_help() {
    echo "A gh extension to help you quickly create codespaces for a predefined repo."
    echo "For more information, see https://github.com/hubwriter/gh-doccs."
    echo
    echo "Usage:"
    echo "  gh $SCRIPTNAME [flags]" >&2
    echo
    echo "Flags:"
    echo "  -h, --help        Display this help message"
    echo "  -v, --version     Display the version of $SCRIPTNAME"
    echo
}

while true; do
  case "$1" in
    -h | --help )
        display_help
        exit 0
        ;;
    -v | --version )
        echo "$SCRIPTNAME version 2.0"
        exit 0
        ;;
    "" )
        break
        ;;
    * )
        echo "Bad option. Use the --help flag for more information."
        exit
        ;;
  esac
done

echo -e "\nCreate a new codespace for the $REPO repo."
read -e -p "Enter a codespace display name: " DISPLAYNAME

if [ "$REQUEST_BRANCH" = true ] ; then
    read -e -p "Enter a name for a new branch (or press Enter to use the default branch): " BRANCH
fi

CREATE_COMMAND="gh cs create -R $REPO --devcontainer-path $DEVCONTAINER -d '$DISPLAYNAME' --idle-timeout $TIMEOUT -m $MACHINE --retention-period $RETENTION"

if [[ "$BRANCH" =~ ( |\') ]]
then
  echo "Branch names cannot contain spaces or single quotes."
  exit 1
elif [ ! -z ${BRANCH+x} ] && [ -n "$BRANCH" ] # If BRANCH is set and not empty
then
  CREATE_COMMAND="$CREATE_COMMAND -b $BRANCH"
  echo "CREATE_COMMAND is $CREATE_COMMAND"
  # Get the SHA for the default branch:
  SHA=$(eval "gh api repos/$REPO/git/ref/heads/main --jq .object.sha")
  # Create a remote branch
  API_CALL="gh api --method POST -H \"Accept: application/vnd.github+json\" /repos/$REPO/git/refs -f ref=\"refs/heads/$BRANCH\" -f sha=\"$SHA\""
  echo; echo $API_CALL
  eval $API_CALL > /dev/null
fi

echo $CREATE_COMMAND; echo
OUTPUT=$(eval $CREATE_COMMAND)

if [ "$OPEN_IN_BROWSER" = true ]
then
  OPEN_COMMAND="gh codespace code -w -c '$OUTPUT'"
else
  OPEN_COMMAND="gh codespace code -c '$OUTPUT'"
fi

if [ ! -z "$OUTPUT" ]
then
  echo "The internal name for your new codespace is: $OUTPUT"
  eval $OPEN_COMMAND
fi
